all: 3-datos.mkv

3-datos.mkv:
	wget https://github.com/MetodosBayesianos/IBC1.2025.2/releases/download/videos/3-datos.mkv

3-habilidad.mkv:
	wget https://github.com/MetodosBayesianos/IBC1.2025.2/releases/download/videos/3-habilidad.mkv
